version: '3'

services:
  nodejs:
    build: .
    container_name: nodejs
    ports: 
      - 3000:3000
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"
    # command: yarn start
